### ISSUE TITLE
Best way to contribute a sample consent form

### ISSUE THREAD

**Issue by cmaumet** [datalad/open-brain-consent#16]
Hi everyone,

With @mdojat, we would like to contribute a sample consent form. 

The consent form is not currently stored online. How would you recommend that we proceed? Should we update the PDF in this repository or do you prefer that we store the PDF somewhere else and then link to it from here?

Thanks!

**Comment by yarikoptic** [comment]
Ideally it should be stored online somewhere, so we could somewhat point to that institution/lab/irb, is it possible?

**Comment by jpellman** [comment]
@cmaumet - I'd suggest storing the consent form at [HAL-Inria](https://hal.inria.fr/).  In addition to ensuring that the PDF would be kept on some form of preservation-level storage, your institutional repository should be able to give you a persistent identifier of some kind (e.g., a [PURL](https://en.wikipedia.org/wiki/Persistent_uniform_resource_locator) or [DOI](https://en.wikipedia.org/wiki/Digital_object_identifier); HAL-Inria seems to prefer HAL Ids, which I am not as familiar with since they look specific to French libraries).  With a persistent identifier, @yarikoptic  would only need to update the Git Annex repository once (rather than being forced to update it every time the consent document was moved to a different URL).

**Comment by yarikoptic** [comment]
That is a great idea on many regards:
- yeap, persistent identifiers would be great
- we should provide a section with clear recommendations to the review boards: https://github.com/datalad/open-brain-consent/issues/17

**Comment by cmaumet** [comment]
Thank you @jpellman, @yarikoptic and sorry for being late on getting back to you. Using HAL indeed seems very appropriate in this case! 

@mdojat's document is now available at: http://www.hal.inserm.fr/medihal-01773015. 

Do I have to install git-annex to add this consent form to open brain consent or is there a simpler way? Thanks in advance!

**Comment by jpellman** [comment]
@yarikoptic, I can work on putting together some quick instructions for what I've been doing with git-annex sometime this weekend and add that to the contributorship guide since right now it's not as obvious how you would perform a pull request for consent forms since not many people use git-annex (if that's something you'd want).

**Comment by yarikoptic** [comment]
"not many " yet! we are working on it ;-)  I guess instructions wouldn't hurt.  Meanwhile we could just ask to file an issue with URL to the file and desired name.
@cmaumet - how should we name this one, since URL is just http://www.hal.inserm.fr/medihal-01773015/document ;-)  All other samples start with the instutute and then a brief description (`Formulaire de consentement permettant le partage de données` is a bit long)

**Comment by cmaumet** [comment]
@jpellman, @yarikoptic: instructions on how to send a PR using git-annex would be great!

@yarikoptic: how about `GIN_consent-fr.pdf` as a name?

**Comment by cmaumet** [comment]
Hello! Just pinging back on this issue. Is there something I can do to help? Thank you!

**Comment by jpellman** [comment]
@cmaumet - There's a PR [here](https://github.com/datalad/open-brain-consent/pull/23/files) with some instructions I wrote up for contributing with git-annex if you want to try your hand at a PR.

**Comment by yarikoptic** [comment]
Thank you @cmaumet  and @jpellman - I will add it now...
